### ISSUE TITLE
Error in XLConnect package loading and susequent code break

### ISSUE THREAD

**Issue by KHartin** [brianhigh/wa-water-quality#1]
The original warning shows up in the first chuck of code run.

Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: JAVA_HOME cannot be determined from the Registry
In addition: Warning messages:
1: package ‘knitr’ was built under R version 3.1.3 
2: package ‘XLConnect’ was built under R version 3.1.3 
3: package ‘XLConnectJars’ was built under R version 3.1.3 
Failed with error:  ‘package ‘XLConnectJars’ could not be loaded’

Then the break becomes apparent after:

library(XLConnect)
Loading required package: XLConnectJars
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: JAVA_HOME cannot be determined from the Registry
In addition: Warning messages:
1: package ‘XLConnect’ was built under R version 3.1.3 
2: package ‘XLConnectJars’ was built under R version 3.1.3 
Error: package ‘XLConnectJars’ could not be loaded

> fluoride <- readWorksheetFromFile(datafileout, sheet=4, header=FALSE,
> -                                   startRow=3, endRow=420)
>   Error: could not find function "readWorksheetFromFile"

**Comment by brianhigh** [comment]
You need to install Java on your system. See:
http://www.r-statistics.com/2012/08/how-to-load-the-rjava-package-after-the-error-java_home-cannot-be-determined-from-the-registry/
https://support.rstudio.com/hc/communities/public/questions/200661617-Package-rJava-could-not-be-loaded

**Comment by KHartin** [comment]
Good catch Brian.  I had found a mention of installing Java, and did so to no avail.  I did not read the fine print that it needed to be the 64 bit version; the default install is the 32 bit version. Got past this error.

**Comment by KHartin** [comment]
Unfortunately it broke on the very next line.

fluoride <- readWorksheetFromFile(datafileout, sheet=4, header=FALSE,
-                                   startRow=3, endRow=420)
  Error: ZipException (Java): invalid entry size (expected 1820 but got 1826 bytes)

I found a mention of something like this here:
http://objectmix.com/weblogic/576546-unknown-error-zipexception-invalid-entry-size-expected-29630-but-got28789-bytes-print.html

**Comment by brianhigh** [comment]
This is fixed in a commit I am about to push. Also, you will need to install RTools, selecting to change the system PATH, and restart RStudio:

```
# NOTE: *** Windows users will need RTools installed first. ***
#       See: http://cran.r-project.org/bin/windows/Rtools/index.html
```

**Comment by brianhigh** [comment]
I added a check for Java and rJava in 9686be7.
